### ISSUE TITLE
Access to login via /index/ crashes the server

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex-v1#5]
When I click on "Backoffice" from the home: [http://localhost:3000/index/](http://localhost:3000/index/)
I get a `ERR_CONNECTION_RESET`, because the server is down:

```
Route error for /index/ 403 - Forbidden: restricted access  from  http://localhost:3000/
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/home/parmentf/dev/castor-core/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/parmentf/dev/castor-core/node_modules/express/lib/response.js:163:12)
    at done (/home/parmentf/dev/castor-core/node_modules/express/lib/response.js:957:10)
    at /home/parmentf/dev/castor-core/node_modules/nunjucks/src/environment.js:22:23
    at RawTask.call (/home/parmentf/dev/castor-core/node_modules/nunjucks/node_modules/asap/asap.js:40:19)
    at flush (/home/parmentf/dev/castor-core/node_modules/nunjucks/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

However, when I use [http://localhost:3000/login.html](http://localhost:3000/login.html) after loading the home page, it works.

**Comment by parmentf** [comment]
Fixed in [castor-core](https://github.com/castorjs/castor-core/commit/83c878f1af40e2169af7cef7a3bc34efa321ff96).
